// 60 element types
export type ElementTypeFragment =
	// Core - Business Layer (13)
	| 'BusinessActor'
	| 'BusinessCollaboration'
	| 'BusinessEvent'
	| 'BusinessFunction'
	| 'BusinessInteraction'
	| 'BusinessInterface'
	| 'BusinessObject'
	| 'BusinessProcess'
	| 'BusinessRole'
	| 'BusinessService'
	| 'Contract'
	| 'Representation'
	| 'Product'
	// Core - Application Layer (9)
	| 'ApplicationComponent'
	| 'ApplicationCollaboration'
	| 'ApplicationEvent'
	| 'ApplicationFunction'
	| 'ApplicationInteraction'
	| 'ApplicationInterface'
	| 'ApplicationProcess'
	| 'ApplicationService'
	| 'DataObject'
	// Motivation Layer (10)
	| 'Assessment'
	| 'Constraint'
	| 'Driver'
	| 'Goal'
	| 'Meaning'
	| 'Outcome'
	| 'Principle'
	| 'Requirement'
	| 'Stakeholder'
	| 'Value'
	// Core - Technology Layer (17)
	| 'Artifact'
	| 'CommunicationNetwork'
	| 'Device'
	| 'DistributionNetwork'
	| 'Equipment'
	| 'Facility'
	| 'Material'
	| 'Node'
	| 'Path'
	| 'SystemSoftware'
	| 'TechnologyCollaboration'
	| 'TechnologyEvent'
	| 'TechnologyFunction'
	| 'TechnologyInteraction'
	| 'TechnologyInterface'
	| 'TechnologyProcess'
	| 'TechnologyService'
	// Implementation & Migration La
	| 'Deliverable'
	| 'Gap'
	| 'ImplementationEvent'
	| 'Plateau'
	| 'WorkPackage'
	// Strategy Layer (4)
	| 'Resource'
	| 'ValueStream'
	| 'Capability'
	| 'CourseOfAction'
	// Composites (2)
	| 'Grouping'
	| 'Location'
