export type ResourceClassFragment =
	| 'model'
	| 'modelReference'
	| 'propertyDef'
	| 'profile'
	| 'image'
	| 'specialization'
	| 'element'
	| 'relationship'
	| 'relationshipConnector'
	| 'viewpoint'
	| 'view'
	| 'organization'
