// 60 element types
export enum ElementTypeEnum {
	// Core - Business Layer (13)
	BusinessActor = 'http://www.opengroup.org/xsd/archimate/3.0/BusinessActor',
	BusinessCollaboration = 'http://www.opengroup.org/xsd/archimate/3.0/BusinessCollaboration',
	BusinessEvent = 'http://www.opengroup.org/xsd/archimate/3.0/BusinessEvent',
	BusinessFunction = 'http://www.opengroup.org/xsd/archimate/3.0/BusinessFunction',
	BusinessInteraction = 'http://www.opengroup.org/xsd/archimate/3.0/BusinessInteraction',
	BusinessInterface = 'http://www.opengroup.org/xsd/archimate/3.0/BusinessInterface',
	BusinessObject = 'http://www.opengroup.org/xsd/archimate/3.0/BusinessObject',
	BusinessProcess = 'http://www.opengroup.org/xsd/archimate/3.0/BusinessProcess',
	BusinessRole = 'http://www.opengroup.org/xsd/archimate/3.0/BusinessRole',
	BusinessService = 'http://www.opengroup.org/xsd/archimate/3.0/BusinessService',
	Contract = 'http://www.opengroup.org/xsd/archimate/3.0/Contract',
	Representation = 'http://www.opengroup.org/xsd/archimate/3.0/Representation',
	Product = 'http://www.opengroup.org/xsd/archimate/3.0/Product',
	// Core - Application Layer (9)
	ApplicationComponent = 'http://www.opengroup.org/xsd/archimate/3.0/ApplicationComponent',
	ApplicationCollaboration = 'http://www.opengroup.org/xsd/archimate/3.0/ApplicationCollaboration',
	ApplicationEvent = 'http://www.opengroup.org/xsd/archimate/3.0/ApplicationEvent',
	ApplicationFunction = 'http://www.opengroup.org/xsd/archimate/3.0/ApplicationFunction',
	ApplicationInteraction = 'http://www.opengroup.org/xsd/archimate/3.0/ApplicationInteraction',
	ApplicationInterface = 'http://www.opengroup.org/xsd/archimate/3.0/ApplicationInterface',
	ApplicationProcess = 'http://www.opengroup.org/xsd/archimate/3.0/ApplicationProcess',
	ApplicationService = 'http://www.opengroup.org/xsd/archimate/3.0/ApplicationService',
	DataObject = 'http://www.opengroup.org/xsd/archimate/3.0/DataObject',

	// Motivation Layer (10)
	Assessment = 'http://www.opengroup.org/xsd/archimate/3.0/Assessment',
	Constraint = 'http://www.opengroup.org/xsd/archimate/3.0/Constraint',
	Driver = 'http://www.opengroup.org/xsd/archimate/3.0/Driver',
	Goal = 'http://www.opengroup.org/xsd/archimate/3.0/Goal',
	Meaning = 'http://www.opengroup.org/xsd/archimate/3.0/Meaning',
	Outcome = 'http://www.opengroup.org/xsd/archimate/3.0/Outcome',
	Principle = 'http://www.opengroup.org/xsd/archimate/3.0/Principle',
	Requirement = 'http://www.opengroup.org/xsd/archimate/3.0/Requirement',
	Stakeholder = 'http://www.opengroup.org/xsd/archimate/3.0/Stakeholder',
	Value = 'http://www.opengroup.org/xsd/archimate/3.0/Value',

	// Core - Technology Layer (17)
	Artifact = 'http://www.opengroup.org/xsd/archimate/3.0/Artifact',
	CommunicationNetwork = 'http://www.opengroup.org/xsd/archimate/3.0/CommunicationNetwork',
	Device = 'http://www.opengroup.org/xsd/archimate/3.0/Device',
	DistributionNetwork = 'http://www.opengroup.org/xsd/archimate/3.0/DistributionNetwork',
	Equipment = 'http://www.opengroup.org/xsd/archimate/3.0/Equipment',
	Facility = 'http://www.opengroup.org/xsd/archimate/3.0/Facility',
	Material = 'http://www.opengroup.org/xsd/archimate/3.0/Material',
	Node = 'http://www.opengroup.org/xsd/archimate/3.0/Node',
	Path = 'http://www.opengroup.org/xsd/archimate/3.0/Path',
	SystemSoftware = 'http://www.opengroup.org/xsd/archimate/3.0/SystemSoftware',
	TechnologyCollaboration = 'http://www.opengroup.org/xsd/archimate/3.0/TechnologyCollaboration',
	TechnologyEvent = 'http://www.opengroup.org/xsd/archimate/3.0/TechnologyEvent',
	TechnologyFunction = 'http://www.opengroup.org/xsd/archimate/3.0/TechnologyFunction',
	TechnologyInteraction = 'http://www.opengroup.org/xsd/archimate/3.0/TechnologyInteraction',
	TechnologyInterface = 'http://www.opengroup.org/xsd/archimate/3.0/TechnologyInterface',
	TechnologyProcess = 'http://www.opengroup.org/xsd/archimate/3.0/TechnologyProcess',
	TechnologyService = 'http://www.opengroup.org/xsd/archimate/3.0/TechnologyService',
	// Implementation & Migration Layer (5)
	Deliverable = 'http://www.opengroup.org/xsd/archimate/3.0/Deliverable',
	Gap = 'http://www.opengroup.org/xsd/archimate/3.0/Gap',
	ImplementationEvent = 'http://www.opengroup.org/xsd/archimate/3.0/ImplementationEvent',
	Plateau = 'http://www.opengroup.org/xsd/archimate/3.0/Plateau',
	WorkPackage = 'http://www.opengroup.org/xsd/archimate/3.0/WorkPackage',
	// Strategy Layer (4)
	Resource = 'http://www.opengroup.org/xsd/archimate/3.0/Resource',
	ValueStream = 'http://www.opengroup.org/xsd/archimate/3.0/ValueStream',
	Capability = 'http://www.opengroup.org/xsd/archimate/3.0/Capability',
	CourseOfAction = 'http://www.opengroup.org/xsd/archimate/3.0/CourseOfAction',
	// Composites (2)
	Grouping = 'http://www.opengroup.org/xsd/archimate/3.0/Grouping',
	Location = 'http://www.opengroup.org/xsd/archimate/3.0/Location',


	AndJunction = 'http://www.opengroup.org/xsd/archimate/3.0/AndJunction',
	OrJunction = 'http://www.opengroup.org/xsd/archimate/3.0/OrJunction',
}